In [2]:
import numpy as np
import torch
A = np.array([[1, 2, 3], [4, 5, 6]])
A = torch.tensor(A)
A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
torch.transpose(A, 1, 0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [9]:
dim0 = 2
dim1 = 4
dim2 = 5
V = np.arange(dim0*dim1*dim2).reshape(dim0, dim1, dim2).astype(np.float32)
# permute for ggml to consume
V

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]]], dtype=float32)

In [11]:
np.transpose(V, (0, 2, 1))

array([[[ 0.,  5., 10., 15.],
        [ 1.,  6., 11., 16.],
        [ 2.,  7., 12., 17.],
        [ 3.,  8., 13., 18.],
        [ 4.,  9., 14., 19.]],

       [[20., 25., 30., 35.],
        [21., 26., 31., 36.],
        [22., 27., 32., 37.],
        [23., 28., 33., 38.],
        [24., 29., 34., 39.]]], dtype=float32)

In [12]:
torch.zeros((1,2))

tensor([[0., 0.]])